const truths = [
    "What is your biggest fear?",
    "Have you ever lied to get out of trouble?",
    "What is your darkest fear?",
    "Who is your crush?",
    "What are your self-conscious about?",
    "What is the scariest dream that you've ever had?",
    "What lie have you told that actually hurt someone?",
    "Why did you break up with your last boyfriend or girlfriend?",
    "What do you look for in a boyfriend or girlfriend?",
    "What do you really hope your parents never find out about you?",
    "When last did you cried and why?",
    "What is the secret that you never told anyone?",
    "What is the biggest mistake you've ever made?",
    "Have you ever cheated on your boyfriend or girlfriend?",
    "When last do you have sex?",
    "What is your best sex position?",
    "Who do you wish to have sex with?",
    "What is the worst thing in your life right now?",
    "What is the craziest thing you have ever done before?",
    "What is a silly fun fact about yourself?",
    "Do you pee in the shower?",
    "What animal best represents you?",
    "Have you ever gotten really drunk and done anything silly?",
    "Who is your crush in the place you work?",
    "Can you have sex with your work crush, if yes or no why?",
    "What is the dumbest thing that you have ever done?",
    "Have you ever peed yourself? If so, when?",
    "What is the most embarrassing thing that your parents have caught you doing?",
    "When was the most inappropriate time that you farted?",
    "What is the most embarrassing nickname that you have had?",
    "What was the last thing you searched on your phone?",
    "Have you ever walked in on your parents having sex?",
    "When was a time that you embarrassed yourself in front of your crush?",
    "Have you ever regretted something you did in order to get a crush's attention?",
    "What are your top three turn-ons?",
    "Who was your first and last kiss?",
    "What was your strangest sex dream?",
    "Who is the last person you had sex with?",
    "What is your ideal romantic Valentine's night?",
    "Which friend's boyfriend do you think is the cutest?",
    "Have you ever had sex with a random person?",
    "Who is the last person you made out with?",
    "What is the naughtiest thing that you've done in public?",
    "Describe your most recent romantic encounter.",
    "What is your biggest sexual fantasy?",
    "What turns you on?",
    "How old were you when you first masturbated?",
    "What do you search for when you watch porn?",
    "How many people have you kissed?",
    "Would you ever date two people at once if you could get away with it? (not cheating, just casually date).",
    "Have you ever sent someone a nude?",
    "Have you ever received nudes?",
    "What's the most flirtatious thing you've ever done?",
    "Have you ever flashed someone?",
    "Have you ever been in a “friends with benefits” situation?",
    "Have you ever practiced kissing in a mirror?",
    "What color and kind of underwear are you wearing right now?",
    "Have you ever had sex in a public place?",
    "How flirty do you think you are around people?",
    "What do you do when you flirt?",
    "How many people have you slept with?",
];

const dares = [
    "Do your best dance for 30 seconds.",
    "Send a funny text to the third person in your contant list.",
    "Jump up and down as high as you can go for a full minute.",
    "Text me the first word that comes to mind.",
    "Post an old selfie on your Instagram story.",
    "Drink a glass of water while upside down.",
    "Do 30 situps.",
    "Cut some of your hair, even if it is just a small strand.",
    "Chew a piece of gum with the wrapper still on.",
    "Make a sandwich blindfolded.",
    "Eat a spoonful of cinnamon.",
    "Go outside and eat a leaf.",
    "What is a silly fact about you? Whatever it is, post it on all your social media account.",
    "Attempt to do a magic trick and take a video of it.",
    "Do four cartwheels in a row.",
    "Break two eggs on your head.",
    "Put five ice cubes down your pants.",
    "Lick the floor.",
    "Dance with no music for 2 minutes.",
    "Text your last boyfriend or girlfriend a picture of your toe.",
    "Juggle 3 random items.",
    "Make a funny face and send a picture of it to your crush.",
    "Drag your butt on the carpet like a dog from one end of the room to the other.",
    "Send the funniest picture of you on your phone to me.",
    "Eat a raw piece of garlic.",
    "Try to lick your elbow.",
    "Howl like a dog for one minute.",
    "Style your hair in a funny way and take a picture of it.",
    "What is an embarrassing fact about you? Whatever it is, post it on social media.",
    "Do the worm dance.",
    "Take a shower with your clothes on.",
    "Eat a snack without using your hands.",
    "Try to fit your fist in your mouth.",
    "Stick your hand in the toilet.",
    "Fill your mouth with water and act as a fountain.",
    "Wear your underwear on your head for five minutes.",
    "Seduce a guy or girl for three minutes.",
    "Dance without your cloth on.",
    "Twerk on me for a minute.",
    "Show me your nude picture.",
    "Lap dance on me for two minutes.",
    "Take off your underwears without flashing.",
    "Crawl on the ground seductively.",
    "Make out with your opposite gender for 3 minutes.",
    "Take off your pants.",
    "Take off your shirt and swing it in the air for a minutes.",
];

function getRandomTruthOrDare() {
    const resultDiv = document.getElementById('result');
    const randomIndex = Math.floor(Math.random() * 2);

    if (randomIndex === 0) {
        resultDiv.innerHTML = `<p>Truth: ${getRandomElement(truths)}</P>`;
    } else {
        resultDiv.innerHTML = `<p>Dare: ${getRandomElement(dares)}</p>`;
    }
}

function getRandomElement(array) {
    return array[Math.floor(Math.random() * array.length)];
}